/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as beet from '@metaplex-foundation/beet'
import * as web3 from '@solana/web3.js'
import * as beetSolana from '@metaplex-foundation/beet-solana'

/**
 * Arguments used to create {@link MerkleZeros}
 * @category Accounts
 * @category generated
 */
export type MerkleZerosArgs = {
  bump: number
  depth: number
  zeros: number[] /* size: 32 */[]
}

export const merkleZerosDiscriminator = [131, 195, 149, 214, 95, 168, 0, 156]
/**
 * Holds the data for the {@link MerkleZeros} Account and provides de/serialization
 * functionality for that data
 *
 * @category Accounts
 * @category generated
 */
export class MerkleZeros implements MerkleZerosArgs {
  private constructor(
    readonly bump: number,
    readonly depth: number,
    readonly zeros: number[] /* size: 32 */[]
  ) {}

  /**
   * Creates a {@link MerkleZeros} instance from the provided args.
   */
  static fromArgs(args: MerkleZerosArgs) {
    return new MerkleZeros(args.bump, args.depth, args.zeros)
  }

  /**
   * Deserializes the {@link MerkleZeros} from the data of the provided {@link web3.AccountInfo}.
   * @returns a tuple of the account data and the offset up to which the buffer was read to obtain it.
   */
  static fromAccountInfo(
    accountInfo: web3.AccountInfo<Buffer>,
    offset = 0
  ): [MerkleZeros, number] {
    return MerkleZeros.deserialize(accountInfo.data, offset)
  }

  /**
   * Retrieves the account info from the provided address and deserializes
   * the {@link MerkleZeros} from its data.
   *
   * @throws Error if no account info is found at the address or if deserialization fails
   */
  static async fromAccountAddress(
    connection: web3.Connection,
    address: web3.PublicKey,
    commitmentOrConfig?: web3.Commitment | web3.GetAccountInfoConfig
  ): Promise<MerkleZeros> {
    const accountInfo = await connection.getAccountInfo(
      address,
      commitmentOrConfig
    )
    if (accountInfo == null) {
      throw new Error(`Unable to find MerkleZeros account at ${address}`)
    }
    return MerkleZeros.fromAccountInfo(accountInfo, 0)[0]
  }

  /**
   * Provides a {@link web3.Connection.getProgramAccounts} config builder,
   * to fetch accounts matching filters that can be specified via that builder.
   *
   * @param programId - the program that owns the accounts we are filtering
   */
  static gpaBuilder(
    programId: web3.PublicKey = new web3.PublicKey(
      '4BEBe7TVDef5Nfdft252mMCSNBBmPLQ2gVXmKvJvSbP1'
    )
  ) {
    return beetSolana.GpaBuilder.fromStruct(programId, merkleZerosBeet)
  }

  /**
   * Deserializes the {@link MerkleZeros} from the provided data Buffer.
   * @returns a tuple of the account data and the offset up to which the buffer was read to obtain it.
   */
  static deserialize(buf: Buffer, offset = 0): [MerkleZeros, number] {
    return merkleZerosBeet.deserialize(buf, offset)
  }

  /**
   * Serializes the {@link MerkleZeros} into a Buffer.
   * @returns a tuple of the created Buffer and the offset up to which the buffer was written to store it.
   */
  serialize(): [Buffer, number] {
    return merkleZerosBeet.serialize({
      accountDiscriminator: merkleZerosDiscriminator,
      ...this,
    })
  }

  /**
   * Returns the byteSize of a {@link Buffer} holding the serialized data of
   * {@link MerkleZeros} for the provided args.
   *
   * @param args need to be provided since the byte size for this account
   * depends on them
   */
  static byteSize(args: MerkleZerosArgs) {
    const instance = MerkleZeros.fromArgs(args)
    return merkleZerosBeet.toFixedFromValue({
      accountDiscriminator: merkleZerosDiscriminator,
      ...instance,
    }).byteSize
  }

  /**
   * Fetches the minimum balance needed to exempt an account holding
   * {@link MerkleZeros} data from rent
   *
   * @param args need to be provided since the byte size for this account
   * depends on them
   * @param connection used to retrieve the rent exemption information
   */
  static async getMinimumBalanceForRentExemption(
    args: MerkleZerosArgs,
    connection: web3.Connection,
    commitment?: web3.Commitment
  ): Promise<number> {
    return connection.getMinimumBalanceForRentExemption(
      MerkleZeros.byteSize(args),
      commitment
    )
  }

  /**
   * Returns a readable version of {@link MerkleZeros} properties
   * and can be used to convert to JSON and/or logging
   */
  pretty() {
    return {
      bump: this.bump,
      depth: this.depth,
      zeros: this.zeros,
    }
  }
}

/**
 * @category Accounts
 * @category generated
 */
export const merkleZerosBeet = new beet.FixableBeetStruct<
  MerkleZeros,
  MerkleZerosArgs & {
    accountDiscriminator: number[] /* size: 8 */
  }
>(
  [
    ['accountDiscriminator', beet.uniformFixedSizeArray(beet.u8, 8)],
    ['bump', beet.u8],
    ['depth', beet.u8],
    ['zeros', beet.array(beet.uniformFixedSizeArray(beet.u8, 32))],
  ],
  MerkleZeros.fromArgs,
  'MerkleZeros'
)
