/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as beet from '@metaplex-foundation/beet'
import * as web3 from '@solana/web3.js'
import * as beetSolana from '@metaplex-foundation/beet-solana'

/**
 * Arguments used to create {@link MerkleNodeState}
 * @category Accounts
 * @category generated
 */
export type MerkleNodeStateArgs = {
  bump: number
  index: beet.bignum
  data: number[] /* size: 32 */
}

export const merkleNodeStateDiscriminator = [128, 10, 91, 27, 14, 215, 131, 202]
/**
 * Holds the data for the {@link MerkleNodeState} Account and provides de/serialization
 * functionality for that data
 *
 * @category Accounts
 * @category generated
 */
export class MerkleNodeState implements MerkleNodeStateArgs {
  private constructor(
    readonly bump: number,
    readonly index: beet.bignum,
    readonly data: number[] /* size: 32 */
  ) {}

  /**
   * Creates a {@link MerkleNodeState} instance from the provided args.
   */
  static fromArgs(args: MerkleNodeStateArgs) {
    return new MerkleNodeState(args.bump, args.index, args.data)
  }

  /**
   * Deserializes the {@link MerkleNodeState} from the data of the provided {@link web3.AccountInfo}.
   * @returns a tuple of the account data and the offset up to which the buffer was read to obtain it.
   */
  static fromAccountInfo(
    accountInfo: web3.AccountInfo<Buffer>,
    offset = 0
  ): [MerkleNodeState, number] {
    return MerkleNodeState.deserialize(accountInfo.data, offset)
  }

  /**
   * Retrieves the account info from the provided address and deserializes
   * the {@link MerkleNodeState} from its data.
   *
   * @throws Error if no account info is found at the address or if deserialization fails
   */
  static async fromAccountAddress(
    connection: web3.Connection,
    address: web3.PublicKey,
    commitmentOrConfig?: web3.Commitment | web3.GetAccountInfoConfig
  ): Promise<MerkleNodeState> {
    const accountInfo = await connection.getAccountInfo(
      address,
      commitmentOrConfig
    )
    if (accountInfo == null) {
      throw new Error(`Unable to find MerkleNodeState account at ${address}`)
    }
    return MerkleNodeState.fromAccountInfo(accountInfo, 0)[0]
  }

  /**
   * Provides a {@link web3.Connection.getProgramAccounts} config builder,
   * to fetch accounts matching filters that can be specified via that builder.
   *
   * @param programId - the program that owns the accounts we are filtering
   */
  static gpaBuilder(
    programId: web3.PublicKey = new web3.PublicKey(
      '4BEBe7TVDef5Nfdft252mMCSNBBmPLQ2gVXmKvJvSbP1'
    )
  ) {
    return beetSolana.GpaBuilder.fromStruct(programId, merkleNodeStateBeet)
  }

  /**
   * Deserializes the {@link MerkleNodeState} from the provided data Buffer.
   * @returns a tuple of the account data and the offset up to which the buffer was read to obtain it.
   */
  static deserialize(buf: Buffer, offset = 0): [MerkleNodeState, number] {
    return merkleNodeStateBeet.deserialize(buf, offset)
  }

  /**
   * Serializes the {@link MerkleNodeState} into a Buffer.
   * @returns a tuple of the created Buffer and the offset up to which the buffer was written to store it.
   */
  serialize(): [Buffer, number] {
    return merkleNodeStateBeet.serialize({
      accountDiscriminator: merkleNodeStateDiscriminator,
      ...this,
    })
  }

  /**
   * Returns the byteSize of a {@link Buffer} holding the serialized data of
   * {@link MerkleNodeState}
   */
  static get byteSize() {
    return merkleNodeStateBeet.byteSize
  }

  /**
   * Fetches the minimum balance needed to exempt an account holding
   * {@link MerkleNodeState} data from rent
   *
   * @param connection used to retrieve the rent exemption information
   */
  static async getMinimumBalanceForRentExemption(
    connection: web3.Connection,
    commitment?: web3.Commitment
  ): Promise<number> {
    return connection.getMinimumBalanceForRentExemption(
      MerkleNodeState.byteSize,
      commitment
    )
  }

  /**
   * Determines if the provided {@link Buffer} has the correct byte size to
   * hold {@link MerkleNodeState} data.
   */
  static hasCorrectByteSize(buf: Buffer, offset = 0) {
    return buf.byteLength - offset === MerkleNodeState.byteSize
  }

  /**
   * Returns a readable version of {@link MerkleNodeState} properties
   * and can be used to convert to JSON and/or logging
   */
  pretty() {
    return {
      bump: this.bump,
      index: (() => {
        const x = <{ toNumber: () => number }>this.index
        if (typeof x.toNumber === 'function') {
          try {
            return x.toNumber()
          } catch (_) {
            return x
          }
        }
        return x
      })(),
      data: this.data,
    }
  }
}

/**
 * @category Accounts
 * @category generated
 */
export const merkleNodeStateBeet = new beet.BeetStruct<
  MerkleNodeState,
  MerkleNodeStateArgs & {
    accountDiscriminator: number[] /* size: 8 */
  }
>(
  [
    ['accountDiscriminator', beet.uniformFixedSizeArray(beet.u8, 8)],
    ['bump', beet.u8],
    ['index', beet.u64],
    ['data', beet.uniformFixedSizeArray(beet.u8, 32)],
  ],
  MerkleNodeState.fromArgs,
  'MerkleNodeState'
)
