/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as beet from '@metaplex-foundation/beet'
import * as web3 from '@solana/web3.js'

/**
 * @category Instructions
 * @category DumpProof
 * @category generated
 */
export const dumpProofStruct = new beet.BeetArgsStruct<{
  instructionDiscriminator: number[] /* size: 8 */
}>(
  [['instructionDiscriminator', beet.uniformFixedSizeArray(beet.u8, 8)]],
  'DumpProofInstructionArgs'
)
/**
 * Accounts required by the _dumpProof_ instruction
 *
 * @property [_writable_, **signer**] signer
 * @property [_writable_] merkle
 * @property [] mint
 * @property [_writable_] pendingProof
 * @category Instructions
 * @category DumpProof
 * @category generated
 */
export type DumpProofInstructionAccounts = {
  signer: web3.PublicKey
  merkle: web3.PublicKey
  mint: web3.PublicKey
  pendingProof: web3.PublicKey
  systemProgram?: web3.PublicKey
  rent?: web3.PublicKey
  anchorRemainingAccounts?: web3.AccountMeta[]
}

export const dumpProofInstructionDiscriminator = [
  227, 181, 116, 210, 129, 96, 117, 135,
]

/**
 * Creates a _DumpProof_ instruction.
 *
 * @param accounts that will be accessed while the instruction is processed
 * @category Instructions
 * @category DumpProof
 * @category generated
 */
export function createDumpProofInstruction(
  accounts: DumpProofInstructionAccounts,
  programId = new web3.PublicKey('4BEBe7TVDef5Nfdft252mMCSNBBmPLQ2gVXmKvJvSbP1')
) {
  const [data] = dumpProofStruct.serialize({
    instructionDiscriminator: dumpProofInstructionDiscriminator,
  })
  const keys: web3.AccountMeta[] = [
    {
      pubkey: accounts.signer,
      isWritable: true,
      isSigner: true,
    },
    {
      pubkey: accounts.merkle,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.mint,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.pendingProof,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.systemProgram ?? web3.SystemProgram.programId,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.rent ?? web3.SYSVAR_RENT_PUBKEY,
      isWritable: false,
      isSigner: false,
    },
  ]

  if (accounts.anchorRemainingAccounts != null) {
    for (const acc of accounts.anchorRemainingAccounts) {
      keys.push(acc)
    }
  }

  const ix = new web3.TransactionInstruction({
    programId,
    keys,
    data,
  })
  return ix
}
