/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as beet from '@metaplex-foundation/beet'
import * as web3 from '@solana/web3.js'

/**
 * @category Instructions
 * @category CloseAddressLookupTable
 * @category generated
 */
export const closeAddressLookupTableStruct = new beet.BeetArgsStruct<{
  instructionDiscriminator: number[] /* size: 8 */
}>(
  [['instructionDiscriminator', beet.uniformFixedSizeArray(beet.u8, 8)]],
  'CloseAddressLookupTableInstructionArgs'
)
/**
 * Accounts required by the _closeAddressLookupTable_ instruction
 *
 * @property [_writable_, **signer**] signer
 * @property [] addressLookupTableProgram
 * @property [_writable_] addressLookupTable
 * @property [_writable_] userAddressLookupTable
 * @category Instructions
 * @category CloseAddressLookupTable
 * @category generated
 */
export type CloseAddressLookupTableInstructionAccounts = {
  signer: web3.PublicKey
  systemProgram?: web3.PublicKey
  addressLookupTableProgram: web3.PublicKey
  addressLookupTable: web3.PublicKey
  userAddressLookupTable: web3.PublicKey
  rent?: web3.PublicKey
  anchorRemainingAccounts?: web3.AccountMeta[]
}

export const closeAddressLookupTableInstructionDiscriminator = [
  177, 46, 58, 36, 157, 194, 183, 58,
]

/**
 * Creates a _CloseAddressLookupTable_ instruction.
 *
 * @param accounts that will be accessed while the instruction is processed
 * @category Instructions
 * @category CloseAddressLookupTable
 * @category generated
 */
export function createCloseAddressLookupTableInstruction(
  accounts: CloseAddressLookupTableInstructionAccounts,
  programId = new web3.PublicKey('4BEBe7TVDef5Nfdft252mMCSNBBmPLQ2gVXmKvJvSbP1')
) {
  const [data] = closeAddressLookupTableStruct.serialize({
    instructionDiscriminator: closeAddressLookupTableInstructionDiscriminator,
  })
  const keys: web3.AccountMeta[] = [
    {
      pubkey: accounts.signer,
      isWritable: true,
      isSigner: true,
    },
    {
      pubkey: accounts.systemProgram ?? web3.SystemProgram.programId,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.addressLookupTableProgram,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.addressLookupTable,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.userAddressLookupTable,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.rent ?? web3.SYSVAR_RENT_PUBKEY,
      isWritable: false,
      isSigner: false,
    },
  ]

  if (accounts.anchorRemainingAccounts != null) {
    for (const acc of accounts.anchorRemainingAccounts) {
      keys.push(acc)
    }
  }

  const ix = new web3.TransactionInstruction({
    programId,
    keys,
    data,
  })
  return ix
}
