/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as beet from '@metaplex-foundation/beet'
import * as web3 from '@solana/web3.js'
import {
  CreateMerkleNodeArgs,
  createMerkleNodeArgsBeet,
} from '../types/CreateMerkleNodeArgs'

/**
 * @category Instructions
 * @category CreateMerkleNode
 * @category generated
 */
export type CreateMerkleNodeInstructionArgs = {
  args: CreateMerkleNodeArgs
}
/**
 * @category Instructions
 * @category CreateMerkleNode
 * @category generated
 */
export const createMerkleNodeStruct = new beet.BeetArgsStruct<
  CreateMerkleNodeInstructionArgs & {
    instructionDiscriminator: number[] /* size: 8 */
  }
>(
  [
    ['instructionDiscriminator', beet.uniformFixedSizeArray(beet.u8, 8)],
    ['args', createMerkleNodeArgsBeet],
  ],
  'CreateMerkleNodeInstructionArgs'
)
/**
 * Accounts required by the _createMerkleNode_ instruction
 *
 * @property [_writable_, **signer**] signer
 * @property [_writable_] merkleNode
 * @category Instructions
 * @category CreateMerkleNode
 * @category generated
 */
export type CreateMerkleNodeInstructionAccounts = {
  signer: web3.PublicKey
  merkleNode: web3.PublicKey
  systemProgram?: web3.PublicKey
  rent?: web3.PublicKey
  anchorRemainingAccounts?: web3.AccountMeta[]
}

export const createMerkleNodeInstructionDiscriminator = [
  83, 14, 251, 223, 124, 56, 204, 105,
]

/**
 * Creates a _CreateMerkleNode_ instruction.
 *
 * @param accounts that will be accessed while the instruction is processed
 * @param args to provide as instruction data to the program
 *
 * @category Instructions
 * @category CreateMerkleNode
 * @category generated
 */
export function createCreateMerkleNodeInstruction(
  accounts: CreateMerkleNodeInstructionAccounts,
  args: CreateMerkleNodeInstructionArgs,
  programId = new web3.PublicKey('4BEBe7TVDef5Nfdft252mMCSNBBmPLQ2gVXmKvJvSbP1')
) {
  const [data] = createMerkleNodeStruct.serialize({
    instructionDiscriminator: createMerkleNodeInstructionDiscriminator,
    ...args,
  })
  const keys: web3.AccountMeta[] = [
    {
      pubkey: accounts.signer,
      isWritable: true,
      isSigner: true,
    },
    {
      pubkey: accounts.merkleNode,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.systemProgram ?? web3.SystemProgram.programId,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.rent ?? web3.SYSVAR_RENT_PUBKEY,
      isWritable: false,
      isSigner: false,
    },
  ]

  if (accounts.anchorRemainingAccounts != null) {
    for (const acc of accounts.anchorRemainingAccounts) {
      keys.push(acc)
    }
  }

  const ix = new web3.TransactionInstruction({
    programId,
    keys,
    data,
  })
  return ix
}
