/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as beet from '@metaplex-foundation/beet'
export type WithdrawArgs = {
  nullifierHash: number[] /* size: 32 */
  proof: number[] /* size: 256 */
  root: number[] /* size: 32 */
}

/**
 * @category userTypes
 * @category generated
 */
export const withdrawArgsBeet = new beet.BeetArgsStruct<WithdrawArgs>(
  [
    ['nullifierHash', beet.uniformFixedSizeArray(beet.u8, 32)],
    ['proof', beet.uniformFixedSizeArray(beet.u8, 256)],
    ['root', beet.uniformFixedSizeArray(beet.u8, 32)],
  ],
  'WithdrawArgs'
)
