/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as beet from '@metaplex-foundation/beet'
import * as web3 from '@solana/web3.js'

/**
 * @category Instructions
 * @category ExtendAddressLookupTable
 * @category generated
 */
export const extendAddressLookupTableStruct = new beet.BeetArgsStruct<{
  instructionDiscriminator: number[] /* size: 8 */
}>(
  [['instructionDiscriminator', beet.uniformFixedSizeArray(beet.u8, 8)]],
  'ExtendAddressLookupTableInstructionArgs'
)
/**
 * Accounts required by the _extendAddressLookupTable_ instruction
 *
 * @property [_writable_, **signer**] signer
 * @property [] addressLookupTableProgram
 * @property [_writable_] addressLookupTable
 * @property [_writable_] userAddressLookupTable
 * @category Instructions
 * @category ExtendAddressLookupTable
 * @category generated
 */
export type ExtendAddressLookupTableInstructionAccounts = {
  signer: web3.PublicKey
  systemProgram?: web3.PublicKey
  addressLookupTableProgram: web3.PublicKey
  addressLookupTable: web3.PublicKey
  userAddressLookupTable: web3.PublicKey
  rent?: web3.PublicKey
  anchorRemainingAccounts?: web3.AccountMeta[]
}

export const extendAddressLookupTableInstructionDiscriminator = [
  251, 61, 236, 47, 121, 159, 253, 159,
]

/**
 * Creates a _ExtendAddressLookupTable_ instruction.
 *
 * @param accounts that will be accessed while the instruction is processed
 * @category Instructions
 * @category ExtendAddressLookupTable
 * @category generated
 */
export function createExtendAddressLookupTableInstruction(
  accounts: ExtendAddressLookupTableInstructionAccounts,
  programId = new web3.PublicKey('4BEBe7TVDef5Nfdft252mMCSNBBmPLQ2gVXmKvJvSbP1')
) {
  const [data] = extendAddressLookupTableStruct.serialize({
    instructionDiscriminator: extendAddressLookupTableInstructionDiscriminator,
  })
  const keys: web3.AccountMeta[] = [
    {
      pubkey: accounts.signer,
      isWritable: true,
      isSigner: true,
    },
    {
      pubkey: accounts.systemProgram ?? web3.SystemProgram.programId,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.addressLookupTableProgram,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.addressLookupTable,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.userAddressLookupTable,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.rent ?? web3.SYSVAR_RENT_PUBKEY,
      isWritable: false,
      isSigner: false,
    },
  ]

  if (accounts.anchorRemainingAccounts != null) {
    for (const acc of accounts.anchorRemainingAccounts) {
      keys.push(acc)
    }
  }

  const ix = new web3.TransactionInstruction({
    programId,
    keys,
    data,
  })
  return ix
}
