[workspace]

[toolchain]
anchor_version = "0.29.0"

[features]
seeds = false
skip-lint = false

[programs.localnet]
zklsol = "4BEBe7TVDef5Nfdft252mMCSNBBmPLQ2gVXmKvJvSbP1"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "/Users/ohaddahan/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json --exit --timeout 1000000 tests/merkle-test.ts"
