/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as beet from '@metaplex-foundation/beet'
import * as web3 from '@solana/web3.js'
import * as beetSolana from '@metaplex-foundation/beet-solana'
import { MerkleProof, merkleProofBeet } from '../types/MerkleProof'

/**
 * Arguments used to create {@link MerklePendingProofState}
 * @category Accounts
 * @category generated
 */
export type MerklePendingProofStateArgs = {
  bump: number
  depth: beet.bignum
  index: beet.bignum
  proof: MerkleProof
}

export const merklePendingProofStateDiscriminator = [
  16, 144, 140, 176, 37, 52, 253, 163,
]
/**
 * Holds the data for the {@link MerklePendingProofState} Account and provides de/serialization
 * functionality for that data
 *
 * @category Accounts
 * @category generated
 */
export class MerklePendingProofState implements MerklePendingProofStateArgs {
  private constructor(
    readonly bump: number,
    readonly depth: beet.bignum,
    readonly index: beet.bignum,
    readonly proof: MerkleProof
  ) {}

  /**
   * Creates a {@link MerklePendingProofState} instance from the provided args.
   */
  static fromArgs(args: MerklePendingProofStateArgs) {
    return new MerklePendingProofState(
      args.bump,
      args.depth,
      args.index,
      args.proof
    )
  }

  /**
   * Deserializes the {@link MerklePendingProofState} from the data of the provided {@link web3.AccountInfo}.
   * @returns a tuple of the account data and the offset up to which the buffer was read to obtain it.
   */
  static fromAccountInfo(
    accountInfo: web3.AccountInfo<Buffer>,
    offset = 0
  ): [MerklePendingProofState, number] {
    return MerklePendingProofState.deserialize(accountInfo.data, offset)
  }

  /**
   * Retrieves the account info from the provided address and deserializes
   * the {@link MerklePendingProofState} from its data.
   *
   * @throws Error if no account info is found at the address or if deserialization fails
   */
  static async fromAccountAddress(
    connection: web3.Connection,
    address: web3.PublicKey,
    commitmentOrConfig?: web3.Commitment | web3.GetAccountInfoConfig
  ): Promise<MerklePendingProofState> {
    const accountInfo = await connection.getAccountInfo(
      address,
      commitmentOrConfig
    )
    if (accountInfo == null) {
      throw new Error(
        `Unable to find MerklePendingProofState account at ${address}`
      )
    }
    return MerklePendingProofState.fromAccountInfo(accountInfo, 0)[0]
  }

  /**
   * Provides a {@link web3.Connection.getProgramAccounts} config builder,
   * to fetch accounts matching filters that can be specified via that builder.
   *
   * @param programId - the program that owns the accounts we are filtering
   */
  static gpaBuilder(
    programId: web3.PublicKey = new web3.PublicKey(
      '4BEBe7TVDef5Nfdft252mMCSNBBmPLQ2gVXmKvJvSbP1'
    )
  ) {
    return beetSolana.GpaBuilder.fromStruct(
      programId,
      merklePendingProofStateBeet
    )
  }

  /**
   * Deserializes the {@link MerklePendingProofState} from the provided data Buffer.
   * @returns a tuple of the account data and the offset up to which the buffer was read to obtain it.
   */
  static deserialize(
    buf: Buffer,
    offset = 0
  ): [MerklePendingProofState, number] {
    return merklePendingProofStateBeet.deserialize(buf, offset)
  }

  /**
   * Serializes the {@link MerklePendingProofState} into a Buffer.
   * @returns a tuple of the created Buffer and the offset up to which the buffer was written to store it.
   */
  serialize(): [Buffer, number] {
    return merklePendingProofStateBeet.serialize({
      accountDiscriminator: merklePendingProofStateDiscriminator,
      ...this,
    })
  }

  /**
   * Returns the byteSize of a {@link Buffer} holding the serialized data of
   * {@link MerklePendingProofState} for the provided args.
   *
   * @param args need to be provided since the byte size for this account
   * depends on them
   */
  static byteSize(args: MerklePendingProofStateArgs) {
    const instance = MerklePendingProofState.fromArgs(args)
    return merklePendingProofStateBeet.toFixedFromValue({
      accountDiscriminator: merklePendingProofStateDiscriminator,
      ...instance,
    }).byteSize
  }

  /**
   * Fetches the minimum balance needed to exempt an account holding
   * {@link MerklePendingProofState} data from rent
   *
   * @param args need to be provided since the byte size for this account
   * depends on them
   * @param connection used to retrieve the rent exemption information
   */
  static async getMinimumBalanceForRentExemption(
    args: MerklePendingProofStateArgs,
    connection: web3.Connection,
    commitment?: web3.Commitment
  ): Promise<number> {
    return connection.getMinimumBalanceForRentExemption(
      MerklePendingProofState.byteSize(args),
      commitment
    )
  }

  /**
   * Returns a readable version of {@link MerklePendingProofState} properties
   * and can be used to convert to JSON and/or logging
   */
  pretty() {
    return {
      bump: this.bump,
      depth: (() => {
        const x = <{ toNumber: () => number }>this.depth
        if (typeof x.toNumber === 'function') {
          try {
            return x.toNumber()
          } catch (_) {
            return x
          }
        }
        return x
      })(),
      index: (() => {
        const x = <{ toNumber: () => number }>this.index
        if (typeof x.toNumber === 'function') {
          try {
            return x.toNumber()
          } catch (_) {
            return x
          }
        }
        return x
      })(),
      proof: this.proof,
    }
  }
}

/**
 * @category Accounts
 * @category generated
 */
export const merklePendingProofStateBeet = new beet.FixableBeetStruct<
  MerklePendingProofState,
  MerklePendingProofStateArgs & {
    accountDiscriminator: number[] /* size: 8 */
  }
>(
  [
    ['accountDiscriminator', beet.uniformFixedSizeArray(beet.u8, 8)],
    ['bump', beet.u8],
    ['depth', beet.u64],
    ['index', beet.u64],
    ['proof', merkleProofBeet],
  ],
  MerklePendingProofState.fromArgs,
  'MerklePendingProofState'
)
