/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as beet from '@metaplex-foundation/beet'
import * as web3 from '@solana/web3.js'
import * as beetSolana from '@metaplex-foundation/beet-solana'

/**
 * Arguments used to create {@link MerkleState}
 * @category Accounts
 * @category generated
 */
export type MerkleStateArgs = {
  bump: number
  depth: beet.bignum
  depositSize: beet.bignum
  numberOfDeposits: beet.bignum
  currentRootIndex: number
  nextIndex: beet.bignum
  lowestPendingProofIndex: beet.bignum
  highestPendingProofIndex: beet.bignum
  roots: number[] /* size: 32 */[]
  filledSubTrees: number[] /* size: 32 */[]
}

export const merkleStateDiscriminator = [206, 169, 210, 196, 54, 110, 7, 217]
/**
 * Holds the data for the {@link MerkleState} Account and provides de/serialization
 * functionality for that data
 *
 * @category Accounts
 * @category generated
 */
export class MerkleState implements MerkleStateArgs {
  private constructor(
    readonly bump: number,
    readonly depth: beet.bignum,
    readonly depositSize: beet.bignum,
    readonly numberOfDeposits: beet.bignum,
    readonly currentRootIndex: number,
    readonly nextIndex: beet.bignum,
    readonly lowestPendingProofIndex: beet.bignum,
    readonly highestPendingProofIndex: beet.bignum,
    readonly roots: number[] /* size: 32 */[],
    readonly filledSubTrees: number[] /* size: 32 */[]
  ) {}

  /**
   * Creates a {@link MerkleState} instance from the provided args.
   */
  static fromArgs(args: MerkleStateArgs) {
    return new MerkleState(
      args.bump,
      args.depth,
      args.depositSize,
      args.numberOfDeposits,
      args.currentRootIndex,
      args.nextIndex,
      args.lowestPendingProofIndex,
      args.highestPendingProofIndex,
      args.roots,
      args.filledSubTrees
    )
  }

  /**
   * Deserializes the {@link MerkleState} from the data of the provided {@link web3.AccountInfo}.
   * @returns a tuple of the account data and the offset up to which the buffer was read to obtain it.
   */
  static fromAccountInfo(
    accountInfo: web3.AccountInfo<Buffer>,
    offset = 0
  ): [MerkleState, number] {
    return MerkleState.deserialize(accountInfo.data, offset)
  }

  /**
   * Retrieves the account info from the provided address and deserializes
   * the {@link MerkleState} from its data.
   *
   * @throws Error if no account info is found at the address or if deserialization fails
   */
  static async fromAccountAddress(
    connection: web3.Connection,
    address: web3.PublicKey,
    commitmentOrConfig?: web3.Commitment | web3.GetAccountInfoConfig
  ): Promise<MerkleState> {
    const accountInfo = await connection.getAccountInfo(
      address,
      commitmentOrConfig
    )
    if (accountInfo == null) {
      throw new Error(`Unable to find MerkleState account at ${address}`)
    }
    return MerkleState.fromAccountInfo(accountInfo, 0)[0]
  }

  /**
   * Provides a {@link web3.Connection.getProgramAccounts} config builder,
   * to fetch accounts matching filters that can be specified via that builder.
   *
   * @param programId - the program that owns the accounts we are filtering
   */
  static gpaBuilder(
    programId: web3.PublicKey = new web3.PublicKey(
      '4BEBe7TVDef5Nfdft252mMCSNBBmPLQ2gVXmKvJvSbP1'
    )
  ) {
    return beetSolana.GpaBuilder.fromStruct(programId, merkleStateBeet)
  }

  /**
   * Deserializes the {@link MerkleState} from the provided data Buffer.
   * @returns a tuple of the account data and the offset up to which the buffer was read to obtain it.
   */
  static deserialize(buf: Buffer, offset = 0): [MerkleState, number] {
    return merkleStateBeet.deserialize(buf, offset)
  }

  /**
   * Serializes the {@link MerkleState} into a Buffer.
   * @returns a tuple of the created Buffer and the offset up to which the buffer was written to store it.
   */
  serialize(): [Buffer, number] {
    return merkleStateBeet.serialize({
      accountDiscriminator: merkleStateDiscriminator,
      ...this,
    })
  }

  /**
   * Returns the byteSize of a {@link Buffer} holding the serialized data of
   * {@link MerkleState} for the provided args.
   *
   * @param args need to be provided since the byte size for this account
   * depends on them
   */
  static byteSize(args: MerkleStateArgs) {
    const instance = MerkleState.fromArgs(args)
    return merkleStateBeet.toFixedFromValue({
      accountDiscriminator: merkleStateDiscriminator,
      ...instance,
    }).byteSize
  }

  /**
   * Fetches the minimum balance needed to exempt an account holding
   * {@link MerkleState} data from rent
   *
   * @param args need to be provided since the byte size for this account
   * depends on them
   * @param connection used to retrieve the rent exemption information
   */
  static async getMinimumBalanceForRentExemption(
    args: MerkleStateArgs,
    connection: web3.Connection,
    commitment?: web3.Commitment
  ): Promise<number> {
    return connection.getMinimumBalanceForRentExemption(
      MerkleState.byteSize(args),
      commitment
    )
  }

  /**
   * Returns a readable version of {@link MerkleState} properties
   * and can be used to convert to JSON and/or logging
   */
  pretty() {
    return {
      bump: this.bump,
      depth: (() => {
        const x = <{ toNumber: () => number }>this.depth
        if (typeof x.toNumber === 'function') {
          try {
            return x.toNumber()
          } catch (_) {
            return x
          }
        }
        return x
      })(),
      depositSize: (() => {
        const x = <{ toNumber: () => number }>this.depositSize
        if (typeof x.toNumber === 'function') {
          try {
            return x.toNumber()
          } catch (_) {
            return x
          }
        }
        return x
      })(),
      numberOfDeposits: (() => {
        const x = <{ toNumber: () => number }>this.numberOfDeposits
        if (typeof x.toNumber === 'function') {
          try {
            return x.toNumber()
          } catch (_) {
            return x
          }
        }
        return x
      })(),
      currentRootIndex: this.currentRootIndex,
      nextIndex: (() => {
        const x = <{ toNumber: () => number }>this.nextIndex
        if (typeof x.toNumber === 'function') {
          try {
            return x.toNumber()
          } catch (_) {
            return x
          }
        }
        return x
      })(),
      lowestPendingProofIndex: (() => {
        const x = <{ toNumber: () => number }>this.lowestPendingProofIndex
        if (typeof x.toNumber === 'function') {
          try {
            return x.toNumber()
          } catch (_) {
            return x
          }
        }
        return x
      })(),
      highestPendingProofIndex: (() => {
        const x = <{ toNumber: () => number }>this.highestPendingProofIndex
        if (typeof x.toNumber === 'function') {
          try {
            return x.toNumber()
          } catch (_) {
            return x
          }
        }
        return x
      })(),
      roots: this.roots,
      filledSubTrees: this.filledSubTrees,
    }
  }
}

/**
 * @category Accounts
 * @category generated
 */
export const merkleStateBeet = new beet.FixableBeetStruct<
  MerkleState,
  MerkleStateArgs & {
    accountDiscriminator: number[] /* size: 8 */
  }
>(
  [
    ['accountDiscriminator', beet.uniformFixedSizeArray(beet.u8, 8)],
    ['bump', beet.u8],
    ['depth', beet.u64],
    ['depositSize', beet.u64],
    ['numberOfDeposits', beet.u64],
    ['currentRootIndex', beet.u8],
    ['nextIndex', beet.u64],
    ['lowestPendingProofIndex', beet.u64],
    ['highestPendingProofIndex', beet.u64],
    ['roots', beet.array(beet.uniformFixedSizeArray(beet.u8, 32))],
    ['filledSubTrees', beet.array(beet.uniformFixedSizeArray(beet.u8, 32))],
  ],
  MerkleState.fromArgs,
  'MerkleState'
)
