/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as beet from '@metaplex-foundation/beet'
export type CreateMerkleNodeArgs = {
  depth: beet.bignum
  index: beet.bignum
  data: number[] /* size: 32 */
}

/**
 * @category userTypes
 * @category generated
 */
export const createMerkleNodeArgsBeet =
  new beet.BeetArgsStruct<CreateMerkleNodeArgs>(
    [
      ['depth', beet.u64],
      ['index', beet.u64],
      ['data', beet.uniformFixedSizeArray(beet.u8, 32)],
    ],
    'CreateMerkleNodeArgs'
  )
