/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as beet from '@metaplex-foundation/beet'
export type DepositArgs = {
  input: number[] /* size: 32 */
}

/**
 * @category userTypes
 * @category generated
 */
export const depositArgsBeet = new beet.BeetArgsStruct<DepositArgs>(
  [['input', beet.uniformFixedSizeArray(beet.u8, 32)]],
  'DepositArgs'
)
