/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as beet from '@metaplex-foundation/beet'
import { MerkleNode, merkleNodeBeet } from './MerkleNode'
export type PathElement = {
  index: beet.bignum
  node: MerkleNode
}

/**
 * @category userTypes
 * @category generated
 */
export const pathElementBeet = new beet.BeetArgsStruct<PathElement>(
  [
    ['index', beet.u64],
    ['node', merkleNodeBeet],
  ],
  'PathElement'
)
