/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as web3 from '@solana/web3.js'
import * as beet from '@metaplex-foundation/beet'
import * as beetSolana from '@metaplex-foundation/beet-solana'

/**
 * Arguments used to create {@link UserAddressLookupTable}
 * @category Accounts
 * @category generated
 */
export type UserAddressLookupTableArgs = {
  bump: number
  signer: web3.PublicKey
  addressLookupTable: web3.PublicKey
  accounts: web3.PublicKey[]
}

export const userAddressLookupTableDiscriminator = [
  28, 183, 129, 166, 216, 32, 90, 100,
]
/**
 * Holds the data for the {@link UserAddressLookupTable} Account and provides de/serialization
 * functionality for that data
 *
 * @category Accounts
 * @category generated
 */
export class UserAddressLookupTable implements UserAddressLookupTableArgs {
  private constructor(
    readonly bump: number,
    readonly signer: web3.PublicKey,
    readonly addressLookupTable: web3.PublicKey,
    readonly accounts: web3.PublicKey[]
  ) {}

  /**
   * Creates a {@link UserAddressLookupTable} instance from the provided args.
   */
  static fromArgs(args: UserAddressLookupTableArgs) {
    return new UserAddressLookupTable(
      args.bump,
      args.signer,
      args.addressLookupTable,
      args.accounts
    )
  }

  /**
   * Deserializes the {@link UserAddressLookupTable} from the data of the provided {@link web3.AccountInfo}.
   * @returns a tuple of the account data and the offset up to which the buffer was read to obtain it.
   */
  static fromAccountInfo(
    accountInfo: web3.AccountInfo<Buffer>,
    offset = 0
  ): [UserAddressLookupTable, number] {
    return UserAddressLookupTable.deserialize(accountInfo.data, offset)
  }

  /**
   * Retrieves the account info from the provided address and deserializes
   * the {@link UserAddressLookupTable} from its data.
   *
   * @throws Error if no account info is found at the address or if deserialization fails
   */
  static async fromAccountAddress(
    connection: web3.Connection,
    address: web3.PublicKey,
    commitmentOrConfig?: web3.Commitment | web3.GetAccountInfoConfig
  ): Promise<UserAddressLookupTable> {
    const accountInfo = await connection.getAccountInfo(
      address,
      commitmentOrConfig
    )
    if (accountInfo == null) {
      throw new Error(
        `Unable to find UserAddressLookupTable account at ${address}`
      )
    }
    return UserAddressLookupTable.fromAccountInfo(accountInfo, 0)[0]
  }

  /**
   * Provides a {@link web3.Connection.getProgramAccounts} config builder,
   * to fetch accounts matching filters that can be specified via that builder.
   *
   * @param programId - the program that owns the accounts we are filtering
   */
  static gpaBuilder(
    programId: web3.PublicKey = new web3.PublicKey(
      '4BEBe7TVDef5Nfdft252mMCSNBBmPLQ2gVXmKvJvSbP1'
    )
  ) {
    return beetSolana.GpaBuilder.fromStruct(
      programId,
      userAddressLookupTableBeet
    )
  }

  /**
   * Deserializes the {@link UserAddressLookupTable} from the provided data Buffer.
   * @returns a tuple of the account data and the offset up to which the buffer was read to obtain it.
   */
  static deserialize(
    buf: Buffer,
    offset = 0
  ): [UserAddressLookupTable, number] {
    return userAddressLookupTableBeet.deserialize(buf, offset)
  }

  /**
   * Serializes the {@link UserAddressLookupTable} into a Buffer.
   * @returns a tuple of the created Buffer and the offset up to which the buffer was written to store it.
   */
  serialize(): [Buffer, number] {
    return userAddressLookupTableBeet.serialize({
      accountDiscriminator: userAddressLookupTableDiscriminator,
      ...this,
    })
  }

  /**
   * Returns the byteSize of a {@link Buffer} holding the serialized data of
   * {@link UserAddressLookupTable} for the provided args.
   *
   * @param args need to be provided since the byte size for this account
   * depends on them
   */
  static byteSize(args: UserAddressLookupTableArgs) {
    const instance = UserAddressLookupTable.fromArgs(args)
    return userAddressLookupTableBeet.toFixedFromValue({
      accountDiscriminator: userAddressLookupTableDiscriminator,
      ...instance,
    }).byteSize
  }

  /**
   * Fetches the minimum balance needed to exempt an account holding
   * {@link UserAddressLookupTable} data from rent
   *
   * @param args need to be provided since the byte size for this account
   * depends on them
   * @param connection used to retrieve the rent exemption information
   */
  static async getMinimumBalanceForRentExemption(
    args: UserAddressLookupTableArgs,
    connection: web3.Connection,
    commitment?: web3.Commitment
  ): Promise<number> {
    return connection.getMinimumBalanceForRentExemption(
      UserAddressLookupTable.byteSize(args),
      commitment
    )
  }

  /**
   * Returns a readable version of {@link UserAddressLookupTable} properties
   * and can be used to convert to JSON and/or logging
   */
  pretty() {
    return {
      bump: this.bump,
      signer: this.signer.toBase58(),
      addressLookupTable: this.addressLookupTable.toBase58(),
      accounts: this.accounts,
    }
  }
}

/**
 * @category Accounts
 * @category generated
 */
export const userAddressLookupTableBeet = new beet.FixableBeetStruct<
  UserAddressLookupTable,
  UserAddressLookupTableArgs & {
    accountDiscriminator: number[] /* size: 8 */
  }
>(
  [
    ['accountDiscriminator', beet.uniformFixedSizeArray(beet.u8, 8)],
    ['bump', beet.u8],
    ['signer', beetSolana.publicKey],
    ['addressLookupTable', beetSolana.publicKey],
    ['accounts', beet.array(beetSolana.publicKey)],
  ],
  UserAddressLookupTable.fromArgs,
  'UserAddressLookupTable'
)
