/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as beet from '@metaplex-foundation/beet'
import * as web3 from '@solana/web3.js'

/**
 * @category Instructions
 * @category CloseMerkle
 * @category generated
 */
export const closeMerkleStruct = new beet.BeetArgsStruct<{
  instructionDiscriminator: number[] /* size: 8 */
}>(
  [['instructionDiscriminator', beet.uniformFixedSizeArray(beet.u8, 8)]],
  'CloseMerkleInstructionArgs'
)
/**
 * Accounts required by the _closeMerkle_ instruction
 *
 * @property [_writable_, **signer**] signer
 * @property [_writable_] merkle
 * @property [_writable_] merkleZeros
 * @category Instructions
 * @category CloseMerkle
 * @category generated
 */
export type CloseMerkleInstructionAccounts = {
  signer: web3.PublicKey
  merkle: web3.PublicKey
  merkleZeros: web3.PublicKey
  systemProgram?: web3.PublicKey
  rent?: web3.PublicKey
  anchorRemainingAccounts?: web3.AccountMeta[]
}

export const closeMerkleInstructionDiscriminator = [
  235, 44, 43, 113, 246, 114, 62, 167,
]

/**
 * Creates a _CloseMerkle_ instruction.
 *
 * @param accounts that will be accessed while the instruction is processed
 * @category Instructions
 * @category CloseMerkle
 * @category generated
 */
export function createCloseMerkleInstruction(
  accounts: CloseMerkleInstructionAccounts,
  programId = new web3.PublicKey('4BEBe7TVDef5Nfdft252mMCSNBBmPLQ2gVXmKvJvSbP1')
) {
  const [data] = closeMerkleStruct.serialize({
    instructionDiscriminator: closeMerkleInstructionDiscriminator,
  })
  const keys: web3.AccountMeta[] = [
    {
      pubkey: accounts.signer,
      isWritable: true,
      isSigner: true,
    },
    {
      pubkey: accounts.merkle,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.merkleZeros,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.systemProgram ?? web3.SystemProgram.programId,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.rent ?? web3.SYSVAR_RENT_PUBKEY,
      isWritable: false,
      isSigner: false,
    },
  ]

  if (accounts.anchorRemainingAccounts != null) {
    for (const acc of accounts.anchorRemainingAccounts) {
      keys.push(acc)
    }
  }

  const ix = new web3.TransactionInstruction({
    programId,
    keys,
    data,
  })
  return ix
}
